apiVersion: v1
kind: LimitRange
metadata:
  name: bookstack
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    min:
      memory: 256Mi
      cpu: 250m
    max:
      memory: 1Gi
      cpu: 1
    type: Container